# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f74396666205c24aedeb01940897176e6e2448f9cf8b14c7535c0c2d07fa3a2e0489898db7a2ac0f381f4316aec9f5e6aab87ce8f7e9f3715d32ae94f27d741

test:
  secret_key_base: 016214f268bb6df22691b286c6e191258e3f84a985d76f293a7fb6e179be4fa4172b2e2fadf1f0e1f4e355919e0c6e4658d72f0689b1658cc3e70606f783eed8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
